# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'CornellParking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CornellParking
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.6'

end
